### PR TITLE
Use controller category, remove cookie usage, fix issue on old versions

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | More details below.
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | More details below.

### Changes
- To get the category ID, I used the `$category` attribute of `CategoryController` and `ProductController`, not the value in cookie.
- I extracted the logic to another function and made it more readable.
- Then I went to check if everything still works on the lowest supported versions and to my surprise, I actually fixed a bug on Product page, where it always showed the default category. Now it works properly. :-)
- I removed the cookie setting logic as it's no longer needed.

before

### How to test
- Test on develop and Prestashop 1.7.1 (use PHP 7.1, this old version does not work on newer PHP versions.)
- Go to BO > Themes > Set layouts > Set left column layout to product page.
- Go to BO > Module positions > Hook new module > Choose this module and displayLeftColumnProduct.
- Try all options in the module and see that it works the same way as before, but  you can test it best if you select `Current category` in module settings.

On develop, everything should work the same with and without the PR.
On 1.7.1, it was broken on product pages before, now it should work the same like on develop.

### CODE REVIEW

**Review by 0x346e3730 — APPROVED** [review]

**Comment by Hlavtox** [comment]
@rmilecki Could you check this bro?

**Comment by rmilecki** [comment]
I was working on refactoring `getWidgetVariables()` too, I had slighlty different idea. I'll provide full review tomorrow.

**Comment by Hlavtox** [comment]
@rmilecki Coooool! I will rebase when I get back from holiday and ping you 🥳

**Comment by SharakPL** [comment]
What about https://github.com/PrestaShop/ps_categorytree/blob/dev/category-tree-branch.tpl? It must be some leftover from old version because I don't see it used anywhere.

**Pull request closed without merging**
