### PR TITLE
Add badges to readme

### PR DESCRIPTION
**Pull request by justeen35**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add badges to readme
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by justeen35** [comment]
Hello ?

**Comment by Progi1984** [comment]
Ping @PrestaShop/committers

**Comment by nicosomb** [comment]
I can approve, but I just want to be sure that we need these badges :)

**Comment by justeen35** [comment]
@nicosomb Same badges as https://raw.githubusercontent.com/PrestaShop/ps_facetedsearch/dev/README.md

Very useful to know quickly important informations about github repository

**Review by nicosomb — APPROVED** [review]
👍

**Comment by matks** [comment]
@Hlavtox and @nicosomb : don't forget the milestone my friends 😄

**Pull request merged**
