### PR TITLE
Use Category::getNestedCategories for getting subcategories

### PR DESCRIPTION
**Pull request by rmilecki**
```
This drops a custom complex SQL query and uses existing helper that
handles all the hard work. This simplifies module code and makes it
cleaner while not changing existing behaviour.

Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
```

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Use Category::getNestedCategories for getting subcategories
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | Browse some categories and make sure tree is correct for each of them. Try changing & verifying different module options (e.g. "Category root", "Maximum depth").

### CODE REVIEW

**Comment by Progi1984** [comment]
@rmilecki  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

**Review by matks — DISMISSED** [review]
Changes will break public API of the module (see https://stackoverflow.com/questions/9463613/what-does-public-api-means-in-semantic-versioning) and cannot be merged like this unless we do a new major version.

**Comment by matks** [comment]
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

If however you are still interested in it, please ping us 😉  we can reopen.

Thank you for your contribution.

**Comment by rmilecki** [comment]
I'd like to go back workiing on this. I've solution that doesn't break backward compatibility.

Can I have this pull request reopened, please? @matks ?

**Comment by kpodemski** [comment]
@rmilecki 👍🏻👍🏻👍🏻

**Comment by rmilecki** [comment]
I reworked my code / pull request to leave `::getTree()` in place (I just deprecated it).

Does this cleanup makes any sense to you?

**Review by Hlavtox — APPROVED** [review]
Looks good 👍

**Comment by Hlavtox** [comment]
@kpodemski Can I send it to QA?

**Review by kpodemski — APPROVED** [review]

**Comment by AureRita** [comment]
hi @rmilecki 

Thank you for your PR, I tested it and all the parameters works perfectly except the Maximum depth as you can see : 

[Untitled_ Jan 9, 2023 3_04 PM.webm](https://user-images.githubusercontent.com/100699445/211326675-7713bbeb-7112-4627-98ad-6d344bba23d7.webm)

I tested it also without the PR and the maximum depth doesn't works too

In this refacto, does the maximum depth should works or all the module should works as before ? 

Waiting for your feedback

**Review by hibatallahAouadni — APPROVED** [review]
Hello @rmilecki 

Thanks for your PR 🚀 
LGTM, QA ✅ 

Thanks!

**Comment by Hlavtox** [comment]
Thanks @rmilecki and @hibatallahAouadni!!

**Comment by rmilecki** [comment]
Thank you!

**Pull request merged**
